### ISSUE TITLE
lib/cachex/spec/validator.ex:36: invalid record specification, expected the record name to be an atom

### ISSUE THREAD

**Issue by joshuataylor** [whitfin/cachex#203]
Running Elixir 1.8.0-rc.0:

```
== Compilation error in file lib/cachex/spec/validator.ex ==
** (CompileError) lib/cachex/spec/validator.ex:36: invalid record specification, expected the record name to be an atom
    (elixir) lib/kernel/typespec.ex:875: Kernel.Typespec.compile_error/2
    (elixir) lib/enum.ex:1431: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1431: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/kernel/typespec.ex:927: Kernel.Typespec.fn_args/5
    (elixir) lib/kernel/typespec.ex:913: Kernel.Typespec.fn_args/6
    (elixir) lib/kernel/typespec.ex:366: Kernel.Typespec.translate_spec/8
    (elixir) lib/enum.ex:1431: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/kernel/typespec.ex:223: Kernel.Typespec.translate_typespecs_for_module/2
```

Looks like the spec needs to be changed?:
```
  @doc """
  Validates a specification record type.

  This will provide runtime validation of types and values contained inside
  the specification records. Although records provide key validation, they
  don't expose much coverage of the provided values.

  This will delegate each record type to a customized validation function.
  """
  @spec valid?(atom, record) :: boolean
```

**Comment by whitfin** [comment]
This appears to be some sort of bizarre Elixir bug, rather than something I should change. I'm going to file an issue on the Elixir repo just for clarification.

**Comment by whitfin** [comment]
@joshuataylor ok, this is confirmed as an issue in Elixir core and has been fixed in master. It should be fine with the later versions of 1.8.0 as they come. More info here: https://github.com/elixir-lang/elixir/issues/8564.

**Comment by joshuataylor** [comment]
Was just testing my small project against 1.8.0-rc.0 to see what needed to be logged. Wasn't sure if I should log it here or the main repo - thanks for the followup!
